# Generated by Django 3.1.6 on 2021-02-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hub_sensors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_name', models.CharField(blank=True, max_length=128, null=True)),
                ('sensor_type', models.PositiveIntegerField(blank=True, choices=[(1, 'gps-tracker'), (2, '2d-way-sensor'), (3, 'DHT22'), (4, 'BMP-Barometer'), (5, 'Ambient-light'), (6, 'Camera')], null=True)),
                ('latest_data', models.JSONField(blank=True, null=True)),
                ('latest_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('owner_hub', models.ManyToManyField(to='accounts.hub_acc')),
            ],
        ),
        migrations.CreateModel(
            name='sensor_data_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.hub_sensors')),
            ],
        ),
    ]
