# Generated by Django 3.1.6 on 2021-02-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210212_1022'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub_sensors',
            name='owner',
        ),
        migrations.AddField(
            model_name='hub_sensors',
            name='owner_hub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.hub_acc'),
            preserve_default=False,
        ),
    ]
