# Generated by Django 3.1.6 on 2021-02-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210212_1022'),
        ('sensors', '0002_auto_20210212_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub_sensors',
            name='owner_hub',
        ),
        migrations.AddField(
            model_name='hub_sensors',
            name='owner_hub',
            field=models.ManyToManyField(to='accounts.hub_acc'),
        ),
    ]
