# Generated by Django 3.1.6 on 2021-02-14 09:05

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210214_0757'),
        ('sensors', '0003_auto_20210212_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_operations',
            fields=[
                ('sensor_data_history_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='sensors.sensor_data_history')),
                ('hub_acc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='accounts.hub_acc')),
                ('hub_sensors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensors.hub_sensors')),
            ],
            bases=('sensors.hub_sensors', 'accounts.hub_acc', 'sensors.sensor_data_history'),
        ),
        migrations.AlterField(
            model_name='hub_sensors',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='get_sensor_data',
            fields=[
                ('db_operations_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensors.db_operations')),
            ],
            bases=(django.views.generic.base.View, 'sensors.db_operations'),
        ),
    ]
