# Generated by Django 3.1.6 on 2021-02-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hub_acc',
            old_name='owner',
            new_name='user',
        ),
    ]
