# Generated by Django 3.1.6 on 2021-02-14 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub_acc',
            name='hub_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=228),
            preserve_default=False,
        ),
    ]
