# Generated by Django 3.1.6 on 2021-02-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210207_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub_acc',
            name='registration_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
