# Generated by Django 3.1.6 on 2021-02-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210207_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub_acc',
            name='passwd',
        ),
        migrations.RemoveField(
            model_name='hub_acc',
            name='username',
        ),
    ]
