# Generated by Django 3.1.6 on 2021-02-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210212_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub_acc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
