# Generated by Django 3.1.6 on 2021-02-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_operations',
            fields=[
                ('sensor_data_history_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='sensors.sensor_data_history')),
                ('hub_acc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='accounts.hub_acc')),
                ('hub_sensors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensors.hub_sensors')),
            ],
            bases=('sensors.hub_sensors', 'accounts.hub_acc', 'sensors.sensor_data_history'),
        ),
    ]
